// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Inventory.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventories")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("inventories_hilo_seq", "inventories")
                .IncrementsBy(10);

            modelBuilder.Entity("Modules.Inventory.Domain.AncillaryData.AncillaryData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<DateTime?>("PackageReceivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("package_received_date");

                    b.Property<int>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<string>("RefStockNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ref_stock_number");

                    b.HasKey("Id")
                        .HasName("pk_ancillary_data");

                    b.HasIndex("RefHomeCenterNumber", "RefStockNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_ancillary_data_hc_stock");

                    b.ToTable("ancillary_data", "inventories");
                });

            modelBuilder.Entity("Modules.Inventory.Domain.HomeCentersCache.HomeCenterCache", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("LotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lot_name");

                    b.Property<int>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<string>("StateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_home_centers_cache");

                    b.HasIndex("RefHomeCenterNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_home_centers_cache_ref_home_center_number");

                    b.ToTable("home_centers_cache", "cache");
                });

            modelBuilder.Entity("Modules.Inventory.Domain.LandCosts.LandCost", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AddToTotal")
                        .HasColumnType("text")
                        .HasColumnName("add_to_total");

                    b.Property<string>("FurnitureTotal")
                        .HasColumnType("text")
                        .HasColumnName("furniture_total");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<int>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<string>("RefStockNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ref_stock_number");

                    b.HasKey("Id")
                        .HasName("pk_land_costs");

                    b.HasIndex("RefHomeCenterNumber", "RefStockNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_land_costs_hc_stock");

                    b.ToTable("land_costs", "inventories");
                });

            modelBuilder.Entity("Modules.Inventory.Domain.LandParcels.LandParcel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "inventories_hilo_seq", "inventories");

                    b.Property<string>("AddToTotal")
                        .HasColumnType("text")
                        .HasColumnName("add_to_total");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address2");

                    b.Property<string>("Appraisal")
                        .HasColumnType("text")
                        .HasColumnName("appraisal");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("county");

                    b.Property<string>("HomeStockNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("home_stock_number");

                    b.Property<string>("LandAge")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("land_age");

                    b.Property<string>("LandCost")
                        .HasColumnType("text")
                        .HasColumnName("land_cost");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("LoanNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("loan_number");

                    b.Property<string>("MapParcel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("map_parcel");

                    b.Property<int>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<string>("RefStockNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ref_stock_number");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<string>("StockType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_type");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_land_parcels");

                    b.HasIndex("RefHomeCenterNumber")
                        .HasDatabaseName("ix_land_parcels_ref_home_center_number");

                    b.HasIndex("RefHomeCenterNumber", "RefStockNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_land_parcels_hc_stock");

                    b.ToTable("land_parcels", "inventories");
                });

            modelBuilder.Entity("Modules.Inventory.Domain.OnLotHomes.OnLotHome", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "inventories_hilo_seq", "inventories");

                    b.Property<string>("BuildType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("build_type");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("condition");

                    b.Property<string>("CurrentRetailPrice")
                        .HasColumnType("text")
                        .HasColumnName("current_retail_price");

                    b.Property<string>("Facility")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("facility");

                    b.Property<string>("LandStockNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("land_stock_number");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<string>("Make")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("integer")
                        .HasColumnName("model_year");

                    b.Property<int?>("NumberOfBathrooms")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_bathrooms");

                    b.Property<int?>("NumberOfBedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_bedrooms");

                    b.Property<string>("OriginalRetailPrice")
                        .HasColumnType("text")
                        .HasColumnName("original_retail_price");

                    b.Property<string>("PurchaseDiscount")
                        .HasColumnType("text")
                        .HasColumnName("purchase_discount");

                    b.Property<int>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<string>("RefStockNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ref_stock_number");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("StockType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stock_type");

                    b.Property<string>("StockedInDate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stocked_in_date");

                    b.Property<string>("TotalInvoiceAmount")
                        .HasColumnType("text")
                        .HasColumnName("total_invoice_amount");

                    b.Property<decimal?>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_on_lot_homes");

                    b.HasIndex("RefHomeCenterNumber")
                        .HasDatabaseName("ix_on_lot_homes_ref_home_center_number");

                    b.HasIndex("RefHomeCenterNumber", "RefStockNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_on_lot_homes_hc_stock");

                    b.ToTable("on_lot_homes", "inventories");
                });

            modelBuilder.Entity("Modules.Inventory.Domain.SaleSummariesCache.SaleSummaryCache", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CurrentRetailPrice")
                        .HasColumnType("text")
                        .HasColumnName("current_retail_price");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("OriginalRetailPrice")
                        .HasColumnType("text")
                        .HasColumnName("original_retail_price");

                    b.Property<DateTime?>("ReceivedInDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_in_date");

                    b.Property<string>("RefStockNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ref_stock_number");

                    b.Property<int?>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.HasKey("Id")
                        .HasName("pk_sale_summaries_cache");

                    b.HasIndex("RefStockNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_sale_summaries_cache_ref_stock_number");

                    b.ToTable("sale_summaries_cache", "cache");
                });

            modelBuilder.Entity("Modules.Inventory.Domain.WheelsAndAxles.WheelsAndAxlesTransaction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("BrakeAxleValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brake_axle_value");

                    b.Property<int>("BrakeAxles")
                        .HasColumnType("integer")
                        .HasColumnName("brake_axles");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("IdlerAxleValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idler_axle_value");

                    b.Property<int>("IdlerAxles")
                        .HasColumnType("integer")
                        .HasColumnName("idler_axles");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<int>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<int>("RefTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_transaction_id");

                    b.Property<string>("StockNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stock_number");

                    b.Property<string>("TotalWheelsAndAxlesValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("total_wheels_and_axles_value");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("WheelValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wheel_value");

                    b.Property<int>("Wheels")
                        .HasColumnType("integer")
                        .HasColumnName("wheels");

                    b.HasKey("Id")
                        .HasName("pk_wheels_and_axles_transactions");

                    b.HasIndex("RefHomeCenterNumber")
                        .HasDatabaseName("ix_wheels_and_axles_ref_home_center_number");

                    b.HasIndex("RefHomeCenterNumber", "RefTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_wheels_and_axles_hc_txn");

                    b.ToTable("wheels_and_axles_transactions", "inventories");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("jsonb")
                        .HasColumnName("affected_columns");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("TraceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", "inventories");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Inbox.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedOnUtc", "NextRetryAtUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_next_retry");

                    b.ToTable("inbox_messages", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Inbox.Persistence.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Outbox.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedOnUtc", "NextRetryAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_next_retry");

                    b.ToTable("outbox_messages", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Outbox.Persistence.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "messaging");
                });
#pragma warning restore 612, 618
        }
    }
}
