using Modules.Sales.Domain;
using Modules.Sales.Domain.Cdc;
using Modules.Sales.Domain.Packages;
using Modules.Sales.Domain.Packages.Details;
using Modules.Sales.Domain.Packages.Lines;
using Rtl.Core.Application.Messaging;
using Rtl.Core.Application.Persistence;
using Rtl.Core.Domain.Results;

namespace Modules.Sales.Application.Packages.UpdatePackageProjectCosts;

// Flow: PUT /api/v1/packages/{packageId}/project-costs → UpdatePackageProjectCostsCommand →
//   preserve auto-generated PCs, replace user-managed PCs from request (PUT semantics) →
//   tax change detection → recalculates GrossProfit.
internal sealed class UpdatePackageProjectCostsCommandHandler(
    IPackageRepository packageRepository,
    ICdcProjectCostQueries cdcProjectCostQueries,
    IUnitOfWork<ISalesModule> unitOfWork)
    : ICommandHandler<UpdatePackageProjectCostsCommand, UpdatePackageProjectCostsResult>
{
    // Well-known auto-generated project cost natural keys — managed by other handlers, not user-editable
    private static readonly HashSet<(int Cat, int Item)> AutoGeneratedKeys =
    [
        (9, 21),  // Use Tax — managed by Tax calculation handler
        (2, 1),   // Land Payoff — managed by Land handler
        (10, 9),  // Trade Over Allowance — managed by Trade-In handler
        (14, 1),  // Seller Paid Closing Cost — managed by Concessions handler
        (1, 28),  // W&A Rental — managed by Home handler
        (1, 29)   // W&A Purchase — managed by Home handler
    ];

    private const int UseTaxCategoryNumber = 9;
    private const int UseTaxItemNumber = 21;

    public async Task<Result<UpdatePackageProjectCostsResult>> Handle(
        UpdatePackageProjectCostsCommand request,
        CancellationToken cancellationToken)
    {
        // Step 1: Load package with all lines + sale context
        var package = await packageRepository.GetByPublicIdWithSaleContextAsync(
            request.PackagePublicId, cancellationToken);

        if (package is null)
        {
            return Result.Failure<UpdatePackageProjectCostsResult>(
                PackageErrors.NotFoundByPublicId(request.PackagePublicId));
        }

        // Build (category-number, item-number) → description lookup from CDC reference data.
        // ItemNumber is only unique within a category, not globally — keying by ItemNumber alone
        // causes ToDictionary to crash when the same ItemNumber appears in multiple categories.
        var categories = await cdcProjectCostQueries.GetCategoriesWithItemsAsync(cancellationToken);
        var itemLookup = categories
            .SelectMany(c => c.Items.Select(i => new { c.CategoryNumber, i.ItemNumber, i.Description }))
            .ToDictionary(x => (x.CategoryNumber, x.ItemNumber), x => x.Description);

        // Step 2: Capture pre-update snapshot for tax change detection (project costs only)
        var oldPcCount = package.Lines.OfType<ProjectCostLine>().Count(l => !l.ShouldExcludeFromPricing);
        var oldPcPrices = package.Lines
            .OfType<ProjectCostLine>()
            .Where(l => !l.ShouldExcludeFromPricing)
            .Select(l => l.SalePrice)
            .OrderBy(p => p)
            .ToList();

        // Step 3: Remove only USER-MANAGED project cost lines (preserve auto-generated)
        var userManagedPCs = package.Lines
            .OfType<ProjectCostLine>()
            .Where(l => !IsAutoGenerated(l))
            .ToList();

        foreach (var pc in userManagedPCs)
        {
            package.RemoveLine(pc);
        }

        // Step 4: Add new user-managed project cost lines from request
        AddProjectCostLines(package, request.Items, itemLookup);

        // Step 5: Tax change detection — compare project cost count AND per-item SalePrice
        var newPcCount = package.Lines.OfType<ProjectCostLine>().Count(l => !l.ShouldExcludeFromPricing);
        var newPcPrices = package.Lines
            .OfType<ProjectCostLine>()
            .Where(l => !l.ShouldExcludeFromPricing)
            .Select(l => l.SalePrice)
            .OrderBy(p => p)
            .ToList();

        if (oldPcCount != newPcCount
            || !oldPcPrices.SequenceEqual(newPcPrices))
        {
            var taxLine = package.Lines.OfType<TaxLine>().SingleOrDefault();
            taxLine?.ClearCalculations();

            RemoveUseTaxProjectCost(package);

            package.FlagForTaxRecalculation();
        }

        // Step 6: Persist
        await unitOfWork.SaveChangesAsync(cancellationToken);

        return new UpdatePackageProjectCostsResult(
            package.GrossProfit,
            package.CommissionableGrossProfit,
            package.MustRecalculateTaxes);
    }

    private static void AddProjectCostLines(
        Package package,
        UpdateProjectCostItemRequest[] items,
        Dictionary<(int CategoryNumber, int ItemNumber), string> itemLookup)
    {
        for (var i = 0; i < items.Length; i++)
        {
            var item = items[i];

            if (!itemLookup.TryGetValue((item.CategoryId, item.ItemId), out var itemDescription))
            {
                // CDC lookup failure — skip this item rather than creating a project cost
                // with an invalid category/item combination which would cascade into pricing errors.
                continue;
            }

            var categoryNumber = item.CategoryId;

            // Skip auto-generated items — these are system-managed by other handlers
            if (AutoGeneratedKeys.Contains((categoryNumber, item.ItemId)))
            {
                continue;
            }

            var details = ProjectCostDetails.Create(
                categoryId: categoryNumber,
                itemId: item.ItemId,
                itemDescription: itemDescription);

            var responsibility = item.Responsibility is not null
                ? Enum.Parse<Responsibility>(item.Responsibility, ignoreCase: true)
                : Responsibility.Seller;

            var line = ProjectCostLine.Create(
                packageId: package.Id,
                salePrice: item.SalePrice,
                estimatedCost: item.EstimatedCost,
                retailSalePrice: item.RetailSalePrice,
                responsibility: responsibility,
                shouldExcludeFromPricing: item.ShouldExcludeFromPricing,
                details: details,
                sortOrder: i);

            package.AddLine(line);
        }
    }

    private static bool IsAutoGenerated(ProjectCostLine line) =>
        line.Details is not null &&
        AutoGeneratedKeys.Contains((line.Details.CategoryId, line.Details.ItemId));

    private static void RemoveUseTaxProjectCost(Package package)
    {
        var useTaxPc = package.Lines
            .OfType<ProjectCostLine>()
            .SingleOrDefault(l =>
                l.Details?.CategoryId == UseTaxCategoryNumber
                && l.Details?.ItemId == UseTaxItemNumber);

        if (useTaxPc is not null)
        {
            package.RemoveLine(useTaxPc);
        }
    }
}
