// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Sales.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Sales.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260217025508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("sales_hilo_seq", "sales")
                .IncrementsBy(10);

            modelBuilder.Entity("Modules.Sales.Domain.AuthorizedUsersCache.AuthorizedUserCache", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.PrimitiveCollection<int[]>("AuthorizedHomeCenters")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("authorized_home_centers");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("employee_number");

                    b.Property<string>("FederatedId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("federated_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retired");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<int>("RefUserId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_user_id");

                    b.HasKey("Id")
                        .HasName("pk_authorized_users_cache");

                    b.HasIndex("FederatedId")
                        .IsUnique()
                        .HasDatabaseName("ix_authorized_users_cache_federated_id")
                        .HasFilter("federated_id IS NOT NULL");

                    b.HasIndex("RefUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_authorized_users_cache_ref_user_id");

                    b.ToTable("authorized_users_cache", "cache");
                });

            modelBuilder.Entity("Modules.Sales.Domain.DeliveryAddresses.DeliveryAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "sales_hilo_seq", "sales");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line_2");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("text")
                        .HasColumnName("address_line_3");

                    b.Property<string>("AddressStyle")
                        .HasColumnType("text")
                        .HasColumnName("address_style");

                    b.Property<string>("AddressType")
                        .HasColumnType("text")
                        .HasColumnName("address_type");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("County")
                        .HasColumnType("text")
                        .HasColumnName("county");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsWithinCityLimits")
                        .HasColumnType("boolean")
                        .HasColumnName("is_within_city_limits");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("OccupancyType")
                        .HasColumnType("text")
                        .HasColumnName("occupancy_type");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_delivery_addresses");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_addresses_public_id");

                    b.HasIndex("SaleId")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_addresses_sale_id");

                    b.ToTable("delivery_addresses", "sales");
                });

            modelBuilder.Entity("Modules.Sales.Domain.FundingCache.FundingRequestCache", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approval_date");

                    b.Property<DateTimeOffset?>("ApprovalExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approval_expiration_date");

                    b.Property<JsonDocument>("FundingKeys")
                        .HasColumnType("jsonb")
                        .HasColumnName("funding_keys");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<int>("LenderId")
                        .HasColumnType("integer")
                        .HasColumnName("lender_id");

                    b.Property<string>("LenderName")
                        .HasColumnType("text")
                        .HasColumnName("lender_name");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    b.Property<int>("RefFundingRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_funding_request_id");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_funding_requests_cache");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_funding_requests_cache_package_id");

                    b.HasIndex("RefFundingRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_funding_requests_cache_ref_funding_request_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_funding_requests_cache_sale_id");

                    b.ToTable("funding_requests_cache", "cache");
                });

            modelBuilder.Entity("Modules.Sales.Domain.InventoryCache.LandParcelCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Appraisal")
                        .HasColumnType("text")
                        .HasColumnName("appraisal");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("County")
                        .HasColumnType("text")
                        .HasColumnName("county");

                    b.Property<string>("LandCost")
                        .HasColumnType("text")
                        .HasColumnName("land_cost");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<int>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<int>("RefLandParcelId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_land_parcel_id");

                    b.Property<string>("RefStockNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ref_stock_number");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("StockType")
                        .HasColumnType("text")
                        .HasColumnName("stock_type");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_land_parcels_cache");

                    b.HasIndex("RefLandParcelId")
                        .IsUnique()
                        .HasDatabaseName("ix_land_parcels_cache_ref_land_parcel_id");

                    b.HasIndex("RefHomeCenterNumber", "RefStockNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_land_parcels_cache_hc_stock");

                    b.ToTable("land_parcels_cache", "cache");
                });

            modelBuilder.Entity("Modules.Sales.Domain.InventoryCache.OnLotHomeCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildType")
                        .HasColumnType("text")
                        .HasColumnName("build_type");

                    b.Property<string>("Condition")
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<string>("CurrentRetailPrice")
                        .HasColumnType("text")
                        .HasColumnName("current_retail_price");

                    b.Property<string>("Facility")
                        .HasColumnType("text")
                        .HasColumnName("facility");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric")
                        .HasColumnName("length");

                    b.Property<string>("Make")
                        .HasColumnType("text")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("integer")
                        .HasColumnName("model_year");

                    b.Property<int?>("NumberOfBathrooms")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_bathrooms");

                    b.Property<int?>("NumberOfBedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_bedrooms");

                    b.Property<string>("OriginalRetailPrice")
                        .HasColumnType("text")
                        .HasColumnName("original_retail_price");

                    b.Property<int>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<int>("RefOnLotHomeId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_on_lot_home_id");

                    b.Property<string>("RefStockNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ref_stock_number");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("StockType")
                        .HasColumnType("text")
                        .HasColumnName("stock_type");

                    b.Property<string>("TotalInvoiceAmount")
                        .HasColumnType("text")
                        .HasColumnName("total_invoice_amount");

                    b.Property<decimal?>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_on_lot_homes_cache");

                    b.HasIndex("RefOnLotHomeId")
                        .IsUnique()
                        .HasDatabaseName("ix_on_lot_homes_cache_ref_on_lot_home_id");

                    b.HasIndex("RefHomeCenterNumber", "RefStockNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_on_lot_homes_cache_hc_stock");

                    b.ToTable("on_lot_homes_cache", "cache");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "sales_hilo_seq", "sales");

                    b.Property<string>("CommissionableGrossProfit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commissionable_gross_profit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("GrossProfit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gross_profit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<bool>("MustRecalculateTaxes")
                        .HasColumnType("boolean")
                        .HasColumnName("must_recalculate_taxes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Ranking")
                        .HasColumnType("integer")
                        .HasColumnName("ranking");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_packages");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_packages_public_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_packages_sale_id");

                    b.ToTable("packages", "packages");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.PackageLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "sales_hilo_seq", "sales");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EstimatedCost")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("line_type");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    b.Property<string>("Responsibility")
                        .HasColumnType("text")
                        .HasColumnName("responsibility");

                    b.Property<string>("RetailSalePrice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retail_sale_price");

                    b.Property<string>("SalePrice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sale_price");

                    b.Property<bool>("ShouldExcludeFromPricing")
                        .HasColumnType("boolean")
                        .HasColumnName("should_exclude_from_pricing");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_package_lines");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_package_lines_package_id");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator<string>("LineType").HasValue("PackageLine");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Modules.Sales.Domain.PartiesCache.PartyCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("HomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("home_center_number");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("LifecycleStage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lifecycle_stage");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("party_type");

                    b.Property<int>("RefPartyId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_party_id");

                    b.Property<Guid>("RefPublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_public_id");

                    b.Property<string>("SalesforceAccountId")
                        .HasColumnType("text")
                        .HasColumnName("salesforce_account_id");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.HasIndex("HomeCenterNumber")
                        .HasDatabaseName("ix_parties_home_center_number");

                    b.HasIndex("RefPartyId")
                        .IsUnique()
                        .HasDatabaseName("ix_parties_ref_party_id");

                    b.HasIndex("RefPublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_parties_ref_public_id");

                    b.ToTable("parties", "cache");
                });

            modelBuilder.Entity("Modules.Sales.Domain.PartiesCache.PartyOrganizationCache", b =>
                {
                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_name");

                    b.HasKey("PartyId")
                        .HasName("pk_party_organizations");

                    b.ToTable("party_organizations", "cache");
                });

            modelBuilder.Entity("Modules.Sales.Domain.PartiesCache.PartyPersonCache", b =>
                {
                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<string>("CoBuyerFirstName")
                        .HasColumnType("text")
                        .HasColumnName("co_buyer_first_name");

                    b.Property<string>("CoBuyerLastName")
                        .HasColumnType("text")
                        .HasColumnName("co_buyer_last_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PrimarySalesPersonFederatedId")
                        .HasColumnType("text")
                        .HasColumnName("primary_sales_person_federated_id");

                    b.Property<string>("PrimarySalesPersonFirstName")
                        .HasColumnType("text")
                        .HasColumnName("primary_sales_person_first_name");

                    b.Property<string>("PrimarySalesPersonLastName")
                        .HasColumnType("text")
                        .HasColumnName("primary_sales_person_last_name");

                    b.Property<string>("SecondarySalesPersonFederatedId")
                        .HasColumnType("text")
                        .HasColumnName("secondary_sales_person_federated_id");

                    b.Property<string>("SecondarySalesPersonFirstName")
                        .HasColumnType("text")
                        .HasColumnName("secondary_sales_person_first_name");

                    b.Property<string>("SecondarySalesPersonLastName")
                        .HasColumnType("text")
                        .HasColumnName("secondary_sales_person_last_name");

                    b.HasKey("PartyId")
                        .HasName("pk_party_persons");

                    b.HasIndex("PrimarySalesPersonFederatedId")
                        .HasDatabaseName("ix_party_persons_primary_sp_federated_id");

                    b.ToTable("party_persons", "cache");
                });

            modelBuilder.Entity("Modules.Sales.Domain.RetailLocations.RetailLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "sales_hilo_seq", "sales");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_type");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("OrganizationMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("organization_metadata");

                    b.Property<int?>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state_code");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_retail_locations");

                    b.HasIndex("RefHomeCenterNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_retail_locations_ref_home_center_number")
                        .HasFilter("ref_home_center_number IS NOT NULL");

                    b.ToTable("retail_locations", "sales");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Sales.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "sales_hilo_seq", "sales");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("RetailLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("retail_location_id");

                    b.Property<int>("SaleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sale_number");

                    b.Property<string>("SaleStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sale_status");

                    b.Property<string>("SaleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sale_type");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_sales_party_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_public_id");

                    b.HasIndex("RetailLocationId")
                        .HasDatabaseName("ix_sales_retail_location_id");

                    b.HasIndex("SaleNumber")
                        .HasDatabaseName("ix_sales_sale_number");

                    b.ToTable("sales", "sales");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("jsonb")
                        .HasColumnName("affected_columns");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("TraceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", "sales");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Inbox.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedOnUtc", "NextRetryAtUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_next_retry");

                    b.ToTable("inbox_messages", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Inbox.Persistence.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Outbox.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedOnUtc", "NextRetryAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_next_retry");

                    b.ToTable("outbox_messages", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Outbox.Persistence.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "messaging");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.CreditLine", b =>
                {
                    b.HasBaseType("Modules.Sales.Domain.Packages.PackageLine");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("credit_details");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator().HasValue("Credit");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.HomeLine", b =>
                {
                    b.HasBaseType("Modules.Sales.Domain.Packages.PackageLine");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("home_details");

                    b.Property<int?>("OnLotHomeId")
                        .HasColumnType("integer")
                        .HasColumnName("on_lot_home_id");

                    b.HasIndex("OnLotHomeId")
                        .HasDatabaseName("ix_package_lines_on_lot_home_id")
                        .HasFilter("on_lot_home_id IS NOT NULL");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator().HasValue("Home");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.InsuranceLine", b =>
                {
                    b.HasBaseType("Modules.Sales.Domain.Packages.PackageLine");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("insurance_details");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator().HasValue("Insurance");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.LandLine", b =>
                {
                    b.HasBaseType("Modules.Sales.Domain.Packages.PackageLine");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("land_details");

                    b.Property<int?>("LandParcelId")
                        .HasColumnType("integer")
                        .HasColumnName("land_parcel_id");

                    b.HasIndex("LandParcelId")
                        .HasDatabaseName("ix_package_lines_land_parcel_id")
                        .HasFilter("land_parcel_id IS NOT NULL");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator().HasValue("Land");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.ProjectCostLine", b =>
                {
                    b.HasBaseType("Modules.Sales.Domain.Packages.PackageLine");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("project_cost_details");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator().HasValue("Project Cost");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.SalesTeamLine", b =>
                {
                    b.HasBaseType("Modules.Sales.Domain.Packages.PackageLine");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("sales_team_details");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator().HasValue("Sales Team");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.TaxLine", b =>
                {
                    b.HasBaseType("Modules.Sales.Domain.Packages.PackageLine");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("tax_details");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator().HasValue("Tax");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.TradeInLine", b =>
                {
                    b.HasBaseType("Modules.Sales.Domain.Packages.PackageLine");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("trade_in_details");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator().HasValue("Trade In");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.WarrantyLine", b =>
                {
                    b.HasBaseType("Modules.Sales.Domain.Packages.PackageLine");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("warranty_details");

                    b.ToTable("package_lines", "packages");

                    b.HasDiscriminator().HasValue("Warranty");
                });

            modelBuilder.Entity("Modules.Sales.Domain.DeliveryAddresses.DeliveryAddress", b =>
                {
                    b.HasOne("Modules.Sales.Domain.Sales.Sale", "Sale")
                        .WithOne("DeliveryAddress")
                        .HasForeignKey("Modules.Sales.Domain.DeliveryAddresses.DeliveryAddress", "SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_addresses_sales_sale_id");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Modules.Sales.Domain.FundingCache.FundingRequestCache", b =>
                {
                    b.HasOne("Modules.Sales.Domain.Packages.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_funding_requests_cache_packages_package_id");

                    b.HasOne("Modules.Sales.Domain.Sales.Sale", "Sale")
                        .WithMany("FundingRequests")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_funding_requests_cache_sales_sale_id");

                    b.Navigation("Package");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Package", b =>
                {
                    b.HasOne("Modules.Sales.Domain.Sales.Sale", "Sale")
                        .WithMany("Packages")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_packages_sales_sale_id");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.PackageLine", b =>
                {
                    b.HasOne("Modules.Sales.Domain.Packages.Package", "Package")
                        .WithMany("Lines")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_package_lines_packages_package_id");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Modules.Sales.Domain.PartiesCache.PartyOrganizationCache", b =>
                {
                    b.HasOne("Modules.Sales.Domain.PartiesCache.PartyCache", "Party")
                        .WithOne("Organization")
                        .HasForeignKey("Modules.Sales.Domain.PartiesCache.PartyOrganizationCache", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_organizations_parties_party_id");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Modules.Sales.Domain.PartiesCache.PartyPersonCache", b =>
                {
                    b.HasOne("Modules.Sales.Domain.PartiesCache.PartyCache", "Party")
                        .WithOne("Person")
                        .HasForeignKey("Modules.Sales.Domain.PartiesCache.PartyPersonCache", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_persons_parties_party_id");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Sales.Sale", b =>
                {
                    b.HasOne("Modules.Sales.Domain.PartiesCache.PartyCache", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_parties_cache_party_id");

                    b.HasOne("Modules.Sales.Domain.RetailLocations.RetailLocation", "RetailLocation")
                        .WithMany("Sales")
                        .HasForeignKey("RetailLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_retail_locations_retail_location_id");

                    b.Navigation("Party");

                    b.Navigation("RetailLocation");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.HomeLine", b =>
                {
                    b.HasOne("Modules.Sales.Domain.InventoryCache.OnLotHomeCache", "OnLotHome")
                        .WithMany()
                        .HasForeignKey("OnLotHomeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_package_lines_on_lot_homes_cache_on_lot_home_id");

                    b.Navigation("OnLotHome");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Lines.LandLine", b =>
                {
                    b.HasOne("Modules.Sales.Domain.InventoryCache.LandParcelCache", "LandParcel")
                        .WithMany()
                        .HasForeignKey("LandParcelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_package_lines_land_parcels_cache_land_parcel_id");

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Packages.Package", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Modules.Sales.Domain.PartiesCache.PartyCache", b =>
                {
                    b.Navigation("Organization");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Modules.Sales.Domain.RetailLocations.RetailLocation", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Modules.Sales.Domain.Sales.Sale", b =>
                {
                    b.Navigation("DeliveryAddress");

                    b.Navigation("FundingRequests");

                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
