using Rtl.Core.Application.Messaging;

namespace Modules.Sales.Application.Packages.GetPackageById;

public sealed record GetPackageByIdQuery(Guid PackagePublicId) : IQuery<PackageDetailResponse>;

// --- Top-level response ---
public sealed record PackageDetailResponse(
    Guid Id,
    string Name,
    int Ranking,
    bool IsPrimaryPackage,
    string Status,
    decimal GrossProfit,
    decimal CommissionableGrossProfit,
    bool MustRecalculateTaxes,
    int[] FundingRequestIds,
    HomeSectionResponse? Home,
    LandSectionResponse? Land,
    TaxSectionResponse? Tax,
    InsuranceSectionResponse? Insurance,
    WarrantySectionResponse? Warranty,
    DownPaymentResponse? DownPayment,
    ConcessionsResponse? Concessions,
    TradeInResponse[] TradeIns,
    SalesTeamMemberResponse[] SalesTeam,
    ProjectCostResponse[] ProjectCosts,
    FundingResponse? Funding);

// --- 1:1 sections ---
public sealed record HomeSectionResponse(
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing,
    bool IsProductRemovedFromInventory,
    string? HomeType,
    string? HomeSourceType,
    string? StockNumber,
    string? Make,
    string? Model,
    int? ModelYear,
    decimal? LengthInFeet,
    decimal? WidthInFeet,
    int? Bedrooms,
    decimal? Bathrooms,
    string? SquareFootage,
    int? NumberOfFloorSections,
    string? ModularType,
    string? BuildType,
    bool? ClaytonBuilt,
    string? Vendor,
    decimal? BaseCost,
    decimal? OptionsCost,
    decimal? FreightCost,
    decimal? InvoiceCost,
    decimal? NetInvoice,
    decimal? GrossCost,
    decimal? TaxIncludedOnInvoice,
    decimal? RebateOnMfgInvoice,
    decimal? StateAssociationAndMhiDues,
    decimal? PartnerAssistance,
    int? NumberOfWheels,
    int? NumberOfAxles,
    string? WheelAndAxlesOption,
    decimal? CarrierFrameDeposit,
    double? DistanceMiles,
    string? PropertyType,
    string? PurchaseOption,
    decimal? ListingPrice,
    string? AccountNumber,
    string? DisplayAccountId,
    string? StreetAddress,
    string? City,
    string? State,
    string? ZipCode,
    string? InventoryReferenceId,
    string[]? SerialNumbers);

public sealed record LandSectionResponse(
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing,
    bool IsProductRemovedFromInventory,
    string LandPurchaseType,
    string? CustomerLandType,
    string? LandInclusion,
    string? TypeOfLandWanted,
    decimal? EstimatedValue,
    decimal? SizeInAcres,
    string? PropertyOwner,
    string? FinancedBy,
    decimal? PayoffAmountFinancing,
    decimal? LandEquity,
    DateTimeOffset? OriginalPurchaseDate,
    decimal? OriginalPurchasePrice,
    string? PropertyOwnerPhoneNumber,
    decimal? PropertyLotRent,
    string? Realtor,
    decimal? PurchasePrice,
    string? LandStockNumber,
    decimal? LandCost,
    decimal? LandSalesPrice,
    int? CommunityNumber,
    string? CommunityName,
    string? CommunityManagerName,
    string? CommunityManagerPhoneNumber,
    string? CommunityManagerEmail,
    decimal? CommunityMonthlyCost);

public sealed record TaxSectionResponse(
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing,
    string? PreviouslyTitled,
    int? TaxExemptionId,
    TaxQuestionAnswerResponse[] StateTaxQuestionAnswers,
    PackageTaxItemResponse[] TaxItems,
    string[]? Errors,
    string? TaxExemptionDescription,
    string? StateCode,
    string? DeliveryCity,
    string? DeliveryCounty,
    string? DeliveryPostalCode,
    bool? DeliveryIsWithinCityLimits);

public sealed record TaxQuestionAnswerResponse(int QuestionNumber, string? QuestionText, bool Answer);

public sealed record PackageTaxItemResponse(string Name, bool IsOverridden, decimal? CalculatedAmount, decimal? ChargedAmount);

public sealed record InsuranceSectionResponse(
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing,
    string InsuranceType,
    decimal CoverageAmount,
    bool HasFoundationOrMasonry,
    bool InParkOrSubdivision,
    bool IsLandOwnedByCustomer,
    bool IsPremiumFinanced,
    int? QuoteId,
    string? CompanyName,
    decimal? MaxCoverage,
    decimal? TotalPremium,
    string? ProviderName,
    int? TempLinkId,
    DateTimeOffset? QuotedAt,
    string? HomeStockNumber,
    int? HomeModelYear,
    decimal? HomeLengthInFeet,
    decimal? HomeWidthInFeet,
    string? HomeCondition,
    string? DeliveryState,
    string? DeliveryPostalCode,
    string? DeliveryCity,
    bool? DeliveryIsWithinCityLimits,
    string? OccupancyType);

public sealed record WarrantySectionResponse(
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing,
    bool WarrantySelected,
    decimal? WarrantyAmount,
    decimal? SalesTaxPremium,
    DateTimeOffset? QuotedAt,
    int? HomeModelYear,
    string? HomeModularType,
    decimal? HomeWidthInFeet,
    string? HomeCondition,
    string? DeliveryState,
    string? DeliveryPostalCode,
    bool? DeliveryIsWithinCityLimits,
    int? HomeCenterNumber);

public sealed record DownPaymentResponse(
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing);

public sealed record ConcessionsResponse(
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing);

// --- 1:many sections ---
public sealed record TradeInResponse(
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing,
    string TradeType,
    int Year,
    string Make,
    string Model,
    decimal? FloorWidth,
    decimal? FloorLength,
    decimal TradeAllowance,
    decimal PayoffAmount,
    decimal BookInAmount);

public sealed record SalesTeamMemberResponse(
    string Role,
    int? AuthorizedUserId,
    int? EmployeeNumber,
    string? EmployeeName,
    int SortOrder,
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing,
    decimal? CommissionSplitPercentage,
    decimal CommissionAmount);

public sealed record ProjectCostResponse(
    decimal SalePrice,
    decimal EstimatedCost,
    decimal RetailSalePrice,
    string? Responsibility,
    bool ShouldExcludeFromPricing,
    int CategoryNumber,
    int ItemId,
    string? ItemDescription,
    int SortOrder,
    string? CategoryDescription,
    bool? CategoryIsCreditConsideration,
    bool? CategoryIsLandDot,
    bool? CategoryRestrictFha,
    bool? CategoryRestrictCss,
    bool? CategoryDisplayForCash,
    string? ItemStatus,
    bool? ItemIsFeeItem,
    bool? ItemIsCssRestricted,
    bool? ItemIsFhaRestricted,
    bool? ItemIsDisplayForCash,
    bool? ItemIsRestrictOptionPrice,
    bool? ItemIsRestrictCssCost,
    bool? ItemIsHopeRefundsIncluded,
    decimal? ItemProfitPercentage);

public sealed record FundingResponse(
    int RefFundingRequestId,
    string FundingRequestStatus,
    decimal RequestAmount,
    int LenderId,
    string? LenderName,
    DateTimeOffset? ApprovalDate,
    DateTimeOffset? ApprovalExpirationDate,
    FundingKeyEntry[]? FundingKeys);

public sealed record FundingKeyEntry(string Key, string? Value);
