// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Customer.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Customer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260224155204_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("customers_hilo_seq", "customers")
                .IncrementsBy(10);

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.ContactPoint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "customers_hilo_seq", "customers");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contact_points");

                    b.HasIndex("PartyId", "Type")
                        .HasDatabaseName("ix_contact_points_party_id_type");

                    b.ToTable("contact_points", "customers");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.Party", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "customers_hilo_seq", "customers");

                    b.Property<int>("HomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("home_center_number");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("LifecycleStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle_stage");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("party_type");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("SalesforceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("salesforce_url");

                    b.Property<DateTimeOffset?>("SourceCreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_created_on");

                    b.Property<DateTimeOffset?>("SourceLastModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_last_modified_on");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.HasIndex("HomeCenterNumber")
                        .HasDatabaseName("ix_parties_home_center_number");

                    b.HasIndex("LifecycleStage")
                        .HasDatabaseName("ix_parties_lifecycle_stage");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("uq_parties_public_id");

                    b.ToTable("parties", "customers");

                    b.HasDiscriminator<string>("PartyType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.PartyIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "customers_hilo_seq", "customers");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer")
                        .HasColumnName("party_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_party_identifiers");

                    b.HasIndex("PartyId", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_party_identifiers_party_id_type");

                    b.HasIndex("Type", "Value")
                        .HasDatabaseName("ix_party_identifiers_type_value");

                    b.ToTable("party_identifiers", "customers");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.SalesAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("SalesPersonId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sales_person_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_assignments");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_assignments_person_id")
                        .HasFilter("role = 'Primary'");

                    b.HasIndex("SalesPersonId")
                        .HasDatabaseName("ix_sales_assignments_sales_person_id");

                    b.HasIndex("PersonId", "SalesPersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_assignments_person_id_sales_person_id");

                    b.ToTable("sales_assignments", "customers");
                });

            modelBuilder.Entity("Modules.Customer.Domain.SalesPersons.SalesPerson", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FederatedId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("federated_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<int?>("LotNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lot_number");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_salespersons");

                    b.HasIndex("FederatedId")
                        .IsUnique()
                        .HasDatabaseName("uq_salespersons_federated_id");

                    b.ToTable("salespersons", "customers");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("jsonb")
                        .HasColumnName("affected_columns");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("TraceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", "customers");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Inbox.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedOnUtc", "NextRetryAtUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_next_retry");

                    b.ToTable("inbox_messages", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Inbox.Persistence.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Outbox.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedOnUtc", "NextRetryAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_next_retry");

                    b.ToTable("outbox_messages", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Outbox.Persistence.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "messaging");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.Organization", b =>
                {
                    b.HasBaseType("Modules.Customer.Domain.Parties.Entities.Party");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("organization_name");

                    b.HasDiscriminator().HasValue("Organization");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.Person", b =>
                {
                    b.HasBaseType("Modules.Customer.Domain.Parties.Entities.Party");

                    b.Property<int?>("CoBuyerPartyId")
                        .HasColumnType("integer")
                        .HasColumnName("co_buyer_party_id");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("date_of_birth");

                    b.HasIndex("CoBuyerPartyId")
                        .HasDatabaseName("ix_parties_co_buyer_party_id");

                    b.HasDiscriminator().HasValue("Person");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.ContactPoint", b =>
                {
                    b.HasOne("Modules.Customer.Domain.Parties.Entities.Party", null)
                        .WithMany("ContactPoints")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_points_parties_party_id");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.Party", b =>
                {
                    b.OwnsOne("Modules.Customer.Domain.Parties.Entities.MailingAddress", "MailingAddress", b1 =>
                        {
                            b1.Property<int>("PartyId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine1")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("mailing_address_line1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("mailing_address_line2");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mailing_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("mailing_country");

                            b1.Property<string>("County")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mailing_county");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("mailing_postal_code");

                            b1.Property<string>("State")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("mailing_state");

                            b1.HasKey("PartyId");

                            b1.ToTable("parties", "customers");

                            b1.WithOwner()
                                .HasForeignKey("PartyId")
                                .HasConstraintName("fk_parties_parties_id");
                        });

                    b.Navigation("MailingAddress");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.PartyIdentifier", b =>
                {
                    b.HasOne("Modules.Customer.Domain.Parties.Entities.Party", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_identifiers_parties_party_id");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.SalesAssignment", b =>
                {
                    b.HasOne("Modules.Customer.Domain.Parties.Entities.Person", "Person")
                        .WithMany("SalesAssignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_assignments_persons_person_id");

                    b.HasOne("Modules.Customer.Domain.SalesPersons.SalesPerson", "SalesPerson")
                        .WithMany()
                        .HasForeignKey("SalesPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_assignments_sales_persons_sales_person_id");

                    b.Navigation("Person");

                    b.Navigation("SalesPerson");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.Person", b =>
                {
                    b.HasOne("Modules.Customer.Domain.Parties.Entities.Party", "CoBuyer")
                        .WithMany()
                        .HasForeignKey("CoBuyerPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parties_parties_co_buyer_party_id");

                    b.OwnsOne("Modules.Customer.Domain.Parties.Entities.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("middle_name");

                            b1.Property<string>("NameExtension")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("name_extension");

                            b1.HasKey("PersonId");

                            b1.ToTable("parties", "customers");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");
                        });

                    b.Navigation("CoBuyer");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.Party", b =>
                {
                    b.Navigation("ContactPoints");

                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("Modules.Customer.Domain.Parties.Entities.Person", b =>
                {
                    b.Navigation("SalesAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
