using System.Net.Http.Json;
using Modules.Sales.Domain.Packages.ProjectCosts;
using Modules.Sales.EndpointTests.Abstractions;
using Modules.Sales.Presentation.Endpoints.V1.Packages;
using Modules.Sales.Presentation.Endpoints.V1.Packages.ProjectCosts;
using Rtl.Core.Presentation.Results;

namespace Modules.Sales.EndpointTests.Packages;

// PUT /api/v1/packages/{packageId}/project-costs
//
// Tests:
// - User-managed PC (Cat 11) -> GP includes the margin
// - Auto-generated key (Cat 9 / Item 21, Use Tax) -> silently filtered out
// - Multiple user PCs -> GP includes both margins
public class UpdatePackageProjectCostsTests(SalesEndpointTestFixture fixture) : SalesEndpointTestBase(fixture)
{
    private async Task SeedRequiredCdcDataAsync()
    {
        await Fixture.SeedCdcProjectCostDataAsync(
            (ProjectCostCategories.Refurbishment, "Refurbishment", ProjectCostItems.Cleaning, "Cleaning"),
            (ProjectCostCategories.Refurbishment, "Refurbishment", ProjectCostItems.RepairRefurb, "Repair/Refurb"),
            (ProjectCostCategories.Decorating, "Decorating", ProjectCostItems.DecoratingDrapes, "Decorating Drapes"),
            (ProjectCostCategories.UseTax, "Use Tax", ProjectCostItems.UseTax, "Use Tax"));
    }

    [Fact]
    public async Task ProjectCosts_UserManaged_IncludedInGp()
    {
        // Arrange — full setup: sale + delivery + package + home + CDC reference data
        await SeedRequiredCdcDataAsync();
        await ArrangeSaleWithHomeAsync(
            homeSalePrice: 80_000m,
            homeEstimatedCost: 60_000m);

        // Act — add a user-managed PC (Cat 11 = Refurbishment, Item 1 = Cleaning)
        var items = new[]
        {
            new ProjectCostLineItem(
                CategoryId: ProjectCostCategories.Refurbishment,
                ItemId: ProjectCostItems.Cleaning,
                SalePrice: 4_000m,
                EstimatedCost: 3_000m,
                RetailSalePrice: 4_000m,
                ShouldExcludeFromPricing: false)
        };

        var response = await Client.PutAsJsonAsync(
            $"/api/v1/packages/{PackageId}/project-costs", items);
        var body = await response.Content.ReadFromJsonAsync<ApiEnvelope<PackageUpdatedResponse>>();

        // Assert
        // GP = (Home SP - Home EC) + (W&A SP - W&A EC) + (PC SP - PC EC)
        //    = (80000 - 60000) + (500 - 300) + (4000 - 3000) = 21200
        Assert.NotNull(body?.Data);                                           // Should have returned updated package data
        Assert.Equal(21_200m, body.Data.GrossProfit);                         // Should include user-managed PC margin in GP

        // Verify the PC was persisted
        var updatedPackage = await GetPackageAsync();
        Assert.Contains(updatedPackage.ProjectCosts,
            pc => pc.CategoryNumber == ProjectCostCategories.Refurbishment
               && pc.ItemId == ProjectCostItems.Cleaning);                    // Should have persisted the user-managed PC
    }

    [Fact]
    public async Task ProjectCosts_AutoGeneratedKey_Rejected()
    {
        // Arrange
        await SeedRequiredCdcDataAsync();
        await ArrangeSaleWithHomeAsync(
            homeSalePrice: 80_000m,
            homeEstimatedCost: 60_000m);

        // Act — try to add an auto-generated PC (Cat 9 / Item 21 = Use Tax)
        var items = new[]
        {
            new ProjectCostLineItem(
                CategoryId: ProjectCostCategories.UseTax,
                ItemId: ProjectCostItems.UseTax,
                SalePrice: 1_000m,
                EstimatedCost: 1_000m,
                RetailSalePrice: 1_000m,
                ShouldExcludeFromPricing: false)
        };

        var response = await Client.PutAsJsonAsync(
            $"/api/v1/packages/{PackageId}/project-costs", items);
        var body = await response.Content.ReadFromJsonAsync<ApiEnvelope<PackageUpdatedResponse>>();

        // Assert — GP should NOT include the Use Tax PC (it should have been filtered)
        // GP = (Home SP - Home EC) + (W&A SP - W&A EC) = (80000 - 60000) + (500 - 300) = 20200
        Assert.NotNull(body?.Data);                                           // Should have returned updated package data
        Assert.Equal(20_200m, body.Data.GrossProfit);                         // Should not include auto-generated PC in GP

        // Verify the Use Tax PC was NOT persisted as a user-managed PC
        var updatedPackage = await GetPackageAsync();
        Assert.DoesNotContain(updatedPackage.ProjectCosts,
            pc => pc.CategoryNumber == ProjectCostCategories.UseTax
               && pc.ItemId == ProjectCostItems.UseTax);                      // Should have filtered out the auto-generated PC
    }

    [Fact]
    public async Task ProjectCosts_MultipleUserPcs()
    {
        // Arrange
        await SeedRequiredCdcDataAsync();
        await ArrangeSaleWithHomeAsync(
            homeSalePrice: 80_000m,
            homeEstimatedCost: 60_000m);

        // Act — add two user-managed PCs
        var items = new[]
        {
            new ProjectCostLineItem(
                CategoryId: ProjectCostCategories.Refurbishment,
                ItemId: ProjectCostItems.Cleaning,
                SalePrice: 4_000m,
                EstimatedCost: 3_000m,
                RetailSalePrice: 4_000m,
                ShouldExcludeFromPricing: false),
            new ProjectCostLineItem(
                CategoryId: ProjectCostCategories.Decorating,
                ItemId: ProjectCostItems.DecoratingDrapes,
                SalePrice: 2_000m,
                EstimatedCost: 1_500m,
                RetailSalePrice: 2_000m,
                ShouldExcludeFromPricing: false)
        };

        var response = await Client.PutAsJsonAsync(
            $"/api/v1/packages/{PackageId}/project-costs", items);
        var body = await response.Content.ReadFromJsonAsync<ApiEnvelope<PackageUpdatedResponse>>();

        // Assert
        // GP = (Home SP - Home EC) + (W&A SP - W&A EC) + (PC1 SP - PC1 EC) + (PC2 SP - PC2 EC)
        //    = (80000 - 60000) + (500 - 300) + (4000 - 3000) + (2000 - 1500) = 21700
        Assert.NotNull(body?.Data);                                           // Should have returned updated package data
        Assert.Equal(21_700m, body.Data.GrossProfit);                         // Should include both user-managed PC margins in GP

        // Verify both PCs were persisted
        var updatedPackage = await GetPackageAsync();
        Assert.Contains(updatedPackage.ProjectCosts,
            pc => pc.CategoryNumber == ProjectCostCategories.Refurbishment
               && pc.ItemId == ProjectCostItems.Cleaning);                    // Should have persisted first PC
        Assert.Contains(updatedPackage.ProjectCosts,
            pc => pc.CategoryNumber == ProjectCostCategories.Decorating
               && pc.ItemId == ProjectCostItems.DecoratingDrapes);            // Should have persisted second PC
    }
}
