// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Organization.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Organization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    partial class OrganizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organizations")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("organizations_hilo_seq", "organizations")
                .IncrementsBy(10);

            modelBuilder.Entity("Modules.Organization.Domain.HomeCenters.HomeCenter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Address1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address2");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("area_code");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("LotDba")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lot_dba");

                    b.Property<string>("LotMdlr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lot_mdlr");

                    b.Property<string>("LotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lot_name");

                    b.Property<string>("LotStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lot_status");

                    b.Property<string>("MailingAddress1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mailing_address1");

                    b.Property<string>("MailingAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mailing_address2");

                    b.Property<string>("MailingCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mailing_city");

                    b.Property<string>("MailingStateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("mailing_state_code");

                    b.Property<string>("MailingZip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mailing_zip");

                    b.Property<int?>("ManagerEmployeeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("manager_employee_number");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RefHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ref_home_center_number");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<string>("StateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_home_centers");

                    b.HasIndex("RefHomeCenterNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_home_centers_ref_home_center_number");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_home_centers_region_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_home_centers_zone_id");

                    b.ToTable("home_centers", "organizations");
                });

            modelBuilder.Entity("Modules.Organization.Domain.ManualAssignments.ManualHomeCenterAssignment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("HomeCenterId")
                        .HasColumnType("integer")
                        .HasColumnName("home_center_id");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<int>("RefAssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_assignment_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_manual_hc_assignments");

                    b.HasIndex("HomeCenterId")
                        .HasDatabaseName("ix_manual_hc_assignments_home_center_id");

                    b.HasIndex("RefAssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_manual_hc_assignments_ref_assignment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_manual_hc_assignments_user_id");

                    b.ToTable("manual_hc_assignments", "organizations");
                });

            modelBuilder.Entity("Modules.Organization.Domain.ManualAssignments.ManualZoneAssignment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("Manager")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manager");

                    b.Property<int>("RefAssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_assignment_id");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_code");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("zone");

                    b.HasKey("Id")
                        .HasName("pk_manual_zone_assignments");

                    b.HasIndex("RefAssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_manual_zone_assignments_ref_assignment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_manual_zone_assignments_user_id");

                    b.ToTable("manual_zone_assignments", "organizations");
                });

            modelBuilder.Entity("Modules.Organization.Domain.Regions.Region", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int?>("DummyHomeCenterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("dummy_home_center_number");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("Manager")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manager");

                    b.Property<string>("RefRegionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ref_region_id");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_code");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.HasIndex("RefRegionId")
                        .IsUnique()
                        .HasDatabaseName("ix_regions_ref_region_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_regions_zone_id");

                    b.ToTable("regions", "organizations");
                });

            modelBuilder.Entity("Modules.Organization.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("display_name");

                    b.Property<string>("DistinguishedName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("distinguished_name");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email_address");

                    b.Property<int?>("EmployeeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("employee_number");

                    b.Property<string>("FederatedId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("federated_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retired");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("Level1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level1");

                    b.Property<string>("Level2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level2");

                    b.Property<string>("Level3")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level3");

                    b.Property<string>("Level4")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level4");

                    b.Property<string>("MiddleInitial")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("middle_initial");

                    b.Property<string>("PositionNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position_number");

                    b.Property<int>("RefUserId")
                        .HasColumnType("integer")
                        .HasColumnName("ref_user_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("UserAccountControl")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_account_control");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.Property<int>("UserRoles")
                        .HasColumnType("integer")
                        .HasColumnName("user_roles");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmployeeNumber")
                        .HasDatabaseName("ix_users_employee_number")
                        .HasFilter("employee_number IS NOT NULL");

                    b.HasIndex("FederatedId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_federated_id")
                        .HasFilter("federated_id IS NOT NULL");

                    b.HasIndex("RefUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_ref_user_id");

                    b.ToTable("users", "organizations");
                });

            modelBuilder.Entity("Modules.Organization.Domain.Users.UserHomeCenter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignment_type");

                    b.Property<int>("HomeCenterId")
                        .HasColumnType("integer")
                        .HasColumnName("home_center_id");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_home_centers");

                    b.HasIndex("HomeCenterId")
                        .HasDatabaseName("ix_user_home_centers_home_center_id");

                    b.HasIndex("UserId", "HomeCenterId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_home_centers_user_id_home_center_id");

                    b.ToTable("user_home_centers", "organizations");
                });

            modelBuilder.Entity("Modules.Organization.Domain.Zones.Zone", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("Manager")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manager");

                    b.Property<string>("RefZoneId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ref_zone_id");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("RefZoneId")
                        .IsUnique()
                        .HasDatabaseName("ix_zones_ref_zone_id");

                    b.ToTable("zones", "organizations");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("jsonb")
                        .HasColumnName("affected_columns");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("TraceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", "organizations");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Inbox.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedOnUtc", "NextRetryAtUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_next_retry");

                    b.ToTable("inbox_messages", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Inbox.Persistence.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Outbox.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedOnUtc", "NextRetryAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_next_retry");

                    b.ToTable("outbox_messages", "messaging");
                });

            modelBuilder.Entity("Rtl.Core.Infrastructure.Outbox.Persistence.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "messaging");
                });

            modelBuilder.Entity("Modules.Organization.Domain.HomeCenters.HomeCenter", b =>
                {
                    b.HasOne("Modules.Organization.Domain.Regions.Region", "Region")
                        .WithMany("HomeCenters")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_home_centers_regions_region_id");

                    b.HasOne("Modules.Organization.Domain.Zones.Zone", "Zone")
                        .WithMany("HomeCenters")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_home_centers_zones_zone_id");

                    b.Navigation("Region");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Modules.Organization.Domain.ManualAssignments.ManualHomeCenterAssignment", b =>
                {
                    b.HasOne("Modules.Organization.Domain.HomeCenters.HomeCenter", "HomeCenter")
                        .WithMany()
                        .HasForeignKey("HomeCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_manual_hc_assignments_home_centers_home_center_id");

                    b.HasOne("Modules.Organization.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_manual_hc_assignments_users_user_id");

                    b.Navigation("HomeCenter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.Organization.Domain.ManualAssignments.ManualZoneAssignment", b =>
                {
                    b.HasOne("Modules.Organization.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_manual_zone_assignments_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.Organization.Domain.Regions.Region", b =>
                {
                    b.HasOne("Modules.Organization.Domain.Zones.Zone", "Zone")
                        .WithMany("Regions")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_regions_zones_zone_id");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Modules.Organization.Domain.Users.UserHomeCenter", b =>
                {
                    b.HasOne("Modules.Organization.Domain.HomeCenters.HomeCenter", "HomeCenter")
                        .WithMany("UserHomeCenters")
                        .HasForeignKey("HomeCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_home_centers_home_centers_home_center_id");

                    b.HasOne("Modules.Organization.Domain.Users.User", "User")
                        .WithMany("UserHomeCenters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_home_centers_users_user_id");

                    b.Navigation("HomeCenter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.Organization.Domain.HomeCenters.HomeCenter", b =>
                {
                    b.Navigation("UserHomeCenters");
                });

            modelBuilder.Entity("Modules.Organization.Domain.Regions.Region", b =>
                {
                    b.Navigation("HomeCenters");
                });

            modelBuilder.Entity("Modules.Organization.Domain.Users.User", b =>
                {
                    b.Navigation("UserHomeCenters");
                });

            modelBuilder.Entity("Modules.Organization.Domain.Zones.Zone", b =>
                {
                    b.Navigation("HomeCenters");

                    b.Navigation("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
